targets:
  $default:
    builders:
      freezed:
        generate_for:
          - "lib/**_usecase.dart"
          - "lib/**_entity.dart"
          - "lib/**_model.dart"
          - "lib/**_form.dart"
          - "lib/**_type.dart"
          - "lib/**/maybe.dart"
          - "lib/**/form_field.dart"
          - "lib/**/result.dart"
          - "lib/**/request_status.dart"
          - "lib/**/environment.dart"
          - "lib/**/product.dart"
      json_serializable:
        generate_for:
          - "lib/**_entity.dart"
      auto_route_generator:auto_route_generator: # this for @RoutePage
        generate_for:
          - "lib/**/**_routes.dart"
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        generate_for:
          - "lib/**/app_router.dart"
